spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spacelab?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: true
        show-sql: true
  security:
    user:
      name: user
      password: user
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 1488
  error:
    include-message: always
    include-binding-errors: always
