server:
  servlet:
    context-path: /spacelab/admin

spring:
  datasource:
    url: jdbc:mysql://spacelab_db:3306/spacelab2?createDatabaseIfNotExist=true
    username: root
    password: root

springdoc:
  packages-to-scan: com.example.spacelab.controller
  packages-to-exclude: com.example.spacelab.repository, com.example.spacelab.service
  paths-to-match: /api/**
  override-with-generic-response: false
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    use-root-path: true
    disable-swagger-default-url: true
    path: /api/swagger-ui
    tryItOutEnabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    filter: true

application:
  frontend-admin-panel:
    hostname: slj.avada-media-dev2.od.ua/spacelab/admin
  frontend-personal-cabinet:
    hostname: slj.avada-media-dev2.od.ua/spacelab/cabinet
  teamwork:
    apiVersion: v3
    baseUrl: https://denisscompany18.teamwork.com
    projectId: 641861
    token: twp_QrGASGXS0eiIr83897z18EQXoWzV
  aws:
    bucket:
      name: spacelab-dp-bucket
    accessKey: AKIAZ6H5HK6QAOMKNFFW
    secretKey: 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