spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spacelab?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: create-drop
        jdbc:
          lob:
            non_contextual_creation: true
        show-sql: true
  security:
    user:
      name: user
      password: user
  output:
    ansi:
      enabled: ALWAYS

springdoc:
  packages-to-scan: com.example.spacelab.controller, com.example.spacelab.model
  packages-to-exclude: com.example.spacelab.repository
  paths-to-match: /api/**
  override-with-generic-response: false
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    filter: true

server:
  port: 1488
  error:
    include-message: always
    include-binding-errors: always
