name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_CONTAINER_NAME: slj_spacelab_admin_api_dperevertov
  DOCKER_CONTAINER_NETWORK: spacelab
  DOCKER_IMAGE: temporalparadox/spacelab_admin_api:deploy_avada
  HOST_PORT: 1489
  DOCKER_PORT: 1489

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      name: Log in to Docker Hub
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: $DOCKER_IMAGE


  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: appleboy/ssh-action@v0.1.10
        name: Stop existing container
        if: ${{ success() || failure() }}
        with:
            host: ${{ secrets.SERVER_HOST }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            script: sudo docker stop $DOCKER_CONTAINER_NAME

      - uses: appleboy/ssh-action@v0.1.10
        name: Delete old container
        if: ${{ success() || failure() }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: sudo docker rm $DOCKER_CONTAINER_NAME

      - uses: appleboy/ssh-action@v0.1.10
        name: Delete old image
        if: ${{ success() || failure() }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: sudo docker rmi $DOCKER_IMAGE

      - uses: appleboy/ssh-action@v0.1.10
        name: Create new container with updated image
        if: ${{ success() || failure() }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: sudo docker run -p $HOST_PORT:$DOCKER_PORT -P --name $DOCKER_CONTAINER_NAME --network $DOCKER_CONTAINER_NETWORK -e SPRING_PROFILES_ACTIVE=prod -d $DOCKER_IMAGE

